export * from './http.interceptor';
export * from './auth.guard';
export * from './api.service.login';
export * from './loader.service';
export * from './api.service.catalog';
export * from './api.service.provider';
export * from './api.service.product';
export * from './api.service.user';
export * from './api.service.purchase';
export * from './api.service.client';
export * from './api.service.sale';
export * from './api.service.expense';
export * from './api.service.role';
export * from './api.service.report';
export * from './api.service.company';
export * from './api.service.session';
export * from './api.service.database';
export * from './privileges';
export * from './utils';

export const pageSize: number = 50;